name: Angular CI Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build --configuration=production

    - name: Zip artifact
      run: |
        cd dist/*
        zip -r ../../release.zip .

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: release.zip
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        token: ${{ secrets.TOKEN }}
        body: |
          Release ${{ github.ref_name }}
          
          ### Installation
          1. Download the zip file
          2. Extract to desired location
          3. Open index.html in a browser